# Generated by Django 2.1.5 on 2020-01-16 15:37

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(default='user', max_length=30)),
                ('is_employee', models.BooleanField(default=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('register_id', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpeg', upload_to=account.models.upload_location)),
                ('resume', models.FileField(blank=True, null=True, upload_to=account.models.upload_file_location)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
