# Generated by Django 2.1.5 on 2020-01-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=60)),
                ('scholarship_link', models.CharField(max_length=80)),
                ('image', models.CharField(max_length=80)),
                ('details', models.CharField(max_length=200)),
                ('apply_data', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=25)),
            ],
        ),
    ]
