# Generated by Django 2.1.5 on 2020-01-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=80)),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_link', models.CharField(max_length=80)),
                ('read_more', models.CharField(max_length=80)),
                ('date', models.CharField(max_length=25)),
            ],
        ),
    ]
